<?php

/**
 * Implements hook_install().
 */
function se_migrate_install() {
  // Set up any content types
  
  // Register Migrations can be done in install hook or any time in code by calling registermigrations
  // Migration::registerMigration(seUserMigration, 'demo_user_migration', array());
}

/**
 * Implements hook_uninstall().
 */
function se_migrate_uninstall() {
  // Deregister migrations
  
  
  // Keep content types as they may be needed.
  
}
